import Head from 'next/head';
import styles from '../styles/home.module.scss';
import Image from 'next/image';
import techsImages from '../../public/images/techs.svg';

export default function Home(): JSX.Element {
  return (
    <>
      <Head>
        <title>Apaixonado por Tecnologia - Douglas F</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}>
        <div className={styles.containerHeader}>
          <section className={styles.ctaText}>
            <h1>Levando você ao próximo nível!</h1>
            <span>Um blog para te levar para o próximo nível de Programação 👊!</span>
            <a>
              <button>COMEÇAR AGORA!</button>
            </a>
          </section>

          <img src="/images/banner-conteudos.png" alt="conteúdoes sujeito programador" />
        </div>

        <hr className={styles.divisor} />

        <div className={styles.sectionContent}>
          <section>
            <h2>Aprenda a criar Aplicativos para Android e iOS</h2>
            <span>
              Você vai descobrir o jeito mais moderno de desenvolver apps nativos para iOS
              e Android
            </span>
          </section>

          <img src="/images/financasApp.png" alt="conteúdos desenvolvimento de apps" />
        </div>

        <hr className={styles.divisor} />

        <div className={styles.sectionContent}>
          <img
            src="/images/webDev.png"
            alt="conteúdos desenvolvimento de aplicações web"
          />
          <section>
            <h2>Aprenda a criar Sistemas web</h2>
            <span>
              Criar sistemas web, sites usando tecnologias mais modernas e requisitadas
              pelo mercado.
            </span>
          </section>
        </div>

        <div className={styles.nextLevelContent}>
          <Image src={techsImages} alt="Tecnologias" />
          <h2>
            Mais de <span className={styles.alunos}>15 mil</span> já levaram sua carreira ao próximo nível.
          </h2>
          <span>E você vai perder a chance de evoluir de uma vez por todas?</span>
          <a href=''>
            <button>ACESSAR TURMA</button>
          </a>
        </div>
      </main>
    </>
  );
}
