import Head from 'next/head';
import styles from '../styles/home.module.scss'

export default function Home(): JSX.Element {
  return (
    <>
      <Head>
        <title>Apaixonado por Tecnolongia - Douglas F</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}>
        <div className={styles.containerHeader}>
          <section className={styles.ctaText}>
            <h1>Levando você ao próximo nível!</h1>
            <span>Um blog para te levar para o próximo nível de Programação 👊!</span>
            <a>
              <button>
                COMEÇAR AGORA!
              </button>
            </a>
          </section>

            <img
              src="/images/banner-conteudos.png"
              alt="conteúdoes sujeito programador"
            />
        </div>
      </main>
    </>
  );
}
